
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates && \
    rm -rf /var/lib/apt/lists/* && \
    groupadd -r appgroup && useradd -r -g appgroup appuser
WORKDIR /app
COPY build/* /app
RUN chown -R appuser:appgroup /app
USER appuser
EXPOSE 9013
ENTRYPOINT ["./das-guardian"]
CMD ["--help"]
